{% set version = "1.2.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeltime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modeltime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modeltime/modeltime_{{ version }}.tar.gz
  sha256: 67657d5a4ad299f8edd1383e70e6ab4504f2ec002681fcc80302958799e6fd78

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dials
    - r-doparallel
    - r-dplyr
    - r-forcats
    - r-foreach
    - r-forecast
    - r-ggplot2
    - r-glue
    - r-gt
    - r-hardhat >=1.0.0
    - r-janitor
    - r-magrittr
    - r-parallelly
    - r-parsnip >=0.2.1
    - r-plotly
    - r-prophet
    - r-purrr
    - r-reactable
    - r-rlang >=0.1.2
    - r-scales
    - r-stanheaders
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidymodels
    - r-tidyverse
    - r-timetk >=2.8.1
    - r-workflows >=1.0.0
    - r-xgboost >=1.2.0.1
    - r-yardstick >=0.0.8
  run:
    - r-base
    - r-cli
    - r-dials
    - r-doparallel
    - r-dplyr
    - r-forcats
    - r-foreach
    - r-forecast
    - r-ggplot2
    - r-glue
    - r-gt
    - r-hardhat >=1.0.0
    - r-janitor
    - r-magrittr
    - r-parallelly
    - r-parsnip >=0.2.1
    - r-plotly
    - r-prophet
    - r-purrr
    - r-reactable
    - r-rlang >=0.1.2
    - r-scales
    - r-stanheaders
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidymodels
    - r-tidyverse
    - r-timetk >=2.8.1
    - r-workflows >=1.0.0
    - r-xgboost >=1.2.0.1
    - r-yardstick >=0.0.8

test:
  commands:
    - $R -e "library('modeltime')"           # [not win]
    - "\"%R%\" -e \"library('modeltime')\""  # [win]

about:
  home: https://github.com/business-science/modeltime
  license: MIT
  summary: "The time series forecasting framework for use with the 'tidymodels' ecosystem. Models include ARIMA, Exponential Smoothing, and additional time series models from the 'forecast' and 'prophet' packages. Refer to \"Forecasting Principles & Practice, Second edition\" (<https://otexts.com/fpp2/>). Refer to \"Prophet:\
    \ forecasting at scale\" (<https://research.fb.com/blog/2017/02/prophet-forecasting-at-scale/>.)."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
